### ISSUE TITLE
TODO webserver

### ISSUE THREAD

**Issue by pierre-24** [pierre-24/cp2k-basis#1]
- [x] favicon
- [x] twitter/fb card
- [x] metadata (of the page)
- [x] access other metadata (source)
- [x] add limits (and use a correct back end for that)
