### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by pierre-24** [pierre-24/cp2k-basis#7]
- [ ] Grammar
- [x] Build and improve library (fixed in #11)
- [ ] Basis set and pseudo file format
- [x] logo in the index of the doc (fixed in #9)
- [x] List of file (#18)
